### ISSUE TITLE
你这Code Generator是怎么回事儿

### ISSUE THREAD

**Issue by AM-young-fun** [klaus01/Centipede#3]
是js生成来的？

**Comment by klaus01** [comment]
是用 Node.js 自己写的，查找 CodeGenerator 目录下的 *.txt 文件生成对应的 *.swift 文件。

*.txt 文件中的内容来自 iOS SDK 源代码。

**Comment by AM-young-fun** [comment]
所以是生成的？？？

**Comment by AM-young-fun** [comment]
node js怎么处理iOS里的weak的。

**Comment by AM-young-fun** [comment]
js那玩意儿也没有weak啊。

**Comment by klaus01** [comment]
js 只是将 UIScrollView.txt 格式文本内容转成 CE_UIScrollView.swift 文件内容，纯文本处理。
