### ISSUE TITLE
为什么extension里可以override？

### ISSUE THREAD

**Issue by woshiccm** [klaus01/Centipede#4]
我本来想把tableview那个文件拖进我的demo里试下的，但是报错，看了下是因为在extension里写了override，我记得苹果是不让在extension里override的，你那框架里为什么不报错？

**Comment by klaus01** [comment]
`extension` 中是可以 `override` 的。

你报错应该是在 `internal override func getDelegateInstance() -> UITableView_Delegate` 这里吧？
这里 `override` 的是 CE_UIScrollView.swift 中的 `getDelegateInstance` 方法。

你拖文件的话，CE_UIScrollView.swift 和 CE_UITableView.swift 要一起才行。

**Comment by woshiccm** [comment]
官方:
Extensions can add new functionality to a type, but they cannot override existing functionality.
还有就是你这个已经用internal修饰了，为啥可以override
internal func getDelegateInstance() -> UIScrollView_Delegate {
        return UIScrollView_Delegate()
    }

**Comment by klaus01** [comment]
官方确实这么说，但这个 `override` 确实能编译通过并且重写了父类的同名方法。

`internal` 修饰的方法是指在当前模块中公共，这有什么问题呢？

**Comment by woshiccm** [comment]
internal我给看错成final了，不好意思
